# Generated by Django 4.2.2 on 2023-07-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_bookmarks_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarks',
            name='image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
