# Generated by Django 4.2.2 on 2023-07-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_bookmarks_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarks',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='favorited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='readed',
            field=models.BooleanField(default=False),
        ),
    ]
